export const generalTable = [
  { msg: "Reactor Core Breach (Ship Explodes)", effects: ["death"] },
  { msg: "Structural Collapse (+3 Damage)", effects: ["damage"], damage: 3 },
  { msg: "Structural Collapse (+3 Damage)", effects: ["damage"], damage: 3 },
  { msg: "Explosion Amidships (+2 damage)", effects: ["damage"], damage: 2 },
  { msg: "Explosion Amidships (+2 damage)", effects: ["damage"], damage: 2 },
  { msg: "Superstructure Hit (+1 damage)", effects: ["damage"], damage: 1 },
  { msg: "Superstructure Hit (+1 damage)", effects: ["damage"], damage: 1 },
  { msg: "Inertial Dampeners Down (+1 damage)", effects: ["damage"], damage: 1 },
  { msg: "Inertial Dampeners Down (+1 damage)", effects: ["damage"], damage: 1 },
  { msg: "Weapons Damaged (Offline until repaired)", effects: ["offline"], offline: "one" },
  { msg: "Weapons Damaged (Offline until repaired)", effects: ["offline"], offline: "one" },
  { msg: "Weapons Damaged (Offline until repaired)", effects: ["offline"], offline: "one" },
  { msg: "Weapons Damaged (Offline until repaired)", effects: ["offline"], offline: "one" },
  { msg: "Radiation Leak (+5% crew casualties)", effects: ["crew"], crew: 5 },
  { msg: "Radiation Leak (+5% crew casualties)", effects: ["crew"], crew: 5 },
  { msg: "Coolant Leak (+5% crew casualties)", effects: ["crew"], crew: 5 },
  { msg: "Coolant Leak (+5% crew casualties)", effects: ["crew"], crew: 5 },
  { msg: "Hull Breach (+5% crew casualties)", effects: ["crew"], crew: 5 },
  { msg: "Hull Breach (+5% crew casualties)", effects: ["crew"], crew: 5 },
  { msg: "Main Fusion Reactors Down (+1 damage)", effects: ["damage"], damage: 1 },
  { msg: "Main Fusion Reactors Down (+1 damage)", effects: ["damage"], damage: 1 },
  { msg: "Auxiliary Fusion Reactors Down (+1 damage)", effects: ["damage"], damage: 1 },
  { msg: "Auxiliary Fusion Reactors Down (+1 damage)", effects: ["damage"], damage: 1 },
  { msg: "Weapon Power Short (Some offline until repaired)", effects: ["offline"], offline: "some" },
  { msg: "Weapon Power Short (Some offline until repaired)", effects: ["offline"], offline: "some" },
  { msg: "Weapon Power Short (Some offline until repaired)", effects: ["offline"], offline: "some" },
  { msg: "Weapon Power Short (Some offline until repaired)", effects: ["offline"], offline: "some" },
  { msg: "Engine Power Short (Drifting for 1 turn)", effects: ["drifting"], drifting: 1 },
  { msg: "Engine Power Short (Drifting for 1 turn)", effects: ["drifting"], drifting: 1 },
  { msg: "Engine Power Short (Drifting for 1 turn)", effects: ["drifting"], drifting: 1 },
  { msg: "Engine Power Short (Drifting for 1 turn)", effects: ["drifting"], drifting: 1 },
  { msg: "Shuttle/Fighter Bay Hit" },
  { msg: "Shuttle/Fighter Bay Hit" },
  { msg: "Main Fire Control Out (Offline for 1 turn)", effects: ["offline"], offline: "all" },
  { msg: "Main Fire Control Out (Offline for 1 turn)", effects: ["offline"], offline: "all" },
  { msg: "Main Scanners Out (Offline for 1 turn)", effects: ["offline"], offline: "all" },
  { msg: "Main Scanners Out (Offline for 1 turn)", effects: ["offline"], offline: "all" },
  { msg: "Maglock/Tractor Beams Down" },
  { msg: "Maglock/Tractor Beams Down" },
  { msg: "Main Bridge Hit (Bridge crew killed, Offline for 1 turn)", effects: ["offline"], offline: "all" },
  { msg: "Main Bridge Hit (Bridge crew killed, Offline for 1 turn)", effects: ["offline"], offline: "all" },
  { msg: "Main Engineering Hit (Drifting for 1 turn)", effects: ["drifting"], drifting: 1 },
  { msg: "Main Engineering Hit (Drifting for 1 turn)", effects: ["drifting"], drifting: 1 },
  { msg: "Warp Engine Hit (No warp movement until repaired)" },
  { msg: "Warp Engine Hit (No warp movement until repaired)" },
  { msg: "Warp Engine Hit (No warp movement until repaired)" },
  { msg: "Warp Engine Hit (No warp movement until repaired)" },
  { msg: "Barracks/Cargo Holds Breached (+5% crew casualties)", effects: ["crew"], crew: 5 },
  { msg: "Barracks/Cargo Holds Breached (+5% crew casualties)", effects: ["crew"], crew: 5 },
  { msg: "Warp Drive Down (No warp movement until repaired)" },
  { msg: "Warp Drive Down (No warp movement until repaired)" },
  { msg: "Crew Quarters Breached (+5% crew casualties)", effects: ["crew"], crew: 5 },
  { msg: "Crew Quarters Breached (+5% crew casualties)", effects: ["crew"], crew: 5 },
  { msg: "Impulse Engines Down (Drifting for 1 turn)", effects: ["drifting"], drifting: 1 },
  { msg: "Impulse Engines Down (Drifting for 1 turn)", effects: ["drifting"], drifting: 1 },
  { msg: "Auxiliary Scanners Out" },
  { msg: "Auxiliary Scanners Out" },
  { msg: "Weapon Power Couplings Down (Offline until repaired)", effects: ["offline"], offline: "all" },
  { msg: "Weapon Power Couplings Down (Offline until repaired)", effects: ["offline"], offline: "all" },
  { msg: "Emergency Power Out" },
  { msg: "Emergency Power Out" },
  { msg: "Primary Life Support Out (+10% crew casualties)", effects: ["crew"], crew: 10 },
  { msg: "Primary Life Support Out (+10% crew casualties)", effects: ["crew"], crew: 10 },
  { msg: "Navigational Deflectors Out (No warp movement until repaired)" },
  { msg: "Navigational Deflectors Out (No warp movement until repaired)" },
  { msg: "Internal Damage (+10% crew casualties)", effects: ["crew"], crew: 10 },
  { msg: "Internal Damage (+10% crew casualties)", effects: ["crew"], crew: 10 },
  { msg: "Main Computer Down (Offline for 1 turn)", effects: ["offline"], offline: "all" },
  { msg: "Main Computer Down (Offline for 1 turn)", effects: ["offline"], offline: "all" },
  { msg: "Internal Damage (+5% crew casualties)", effects: ["crew"], crew: 5 },
  { msg: "Internal Damage (+5% crew casualties)", effects: ["crew"], crew: 5 },
  { msg: "Emergency Life Support Out (+5% crew casualties)", effects: ["crew"], crew: 5 },
  { msg: "Emergency Life Support Out (+5% crew casualties)", effects: ["crew"], crew: 5 },
  { msg: "Auxiliary Computer Down" },
  { msg: "Auxiliary Fire Control Out" },
  { msg: "Fire: Level 1 (+1 damage)", effects: ["damage"], damage: 1 },
  { msg: "Fire: Level 1 (+1 damage)", effects: ["damage"], damage: 1 },
  { msg: "Explosion Amidships (+1 damage)", effects: ["damage"], damage: 1 },
  { msg: "Explosion Amidships (+1 damage)", effects: ["damage"], damage: 1 },
  { msg: "ECM/Cloaking Systems Out" },
  { msg: "ECM/Cloaking Systems Out" },
  { msg: "Fire: Level 2 (+2 damage)", effects: ["damage"], damage: 2 },
  { msg: "Fire: Level 2 (+2 damage)", effects: ["damage"], damage: 2 },
  { msg: "Explosion Amidships (+2 damage)", effects: ["damage"], damage: 2 },
  { msg: "Explosion Amidships (+2 damage)", effects: ["damage"], damage: 2 },
  { msg: "Ammunition Bay/Magazine Explosion (+Tp damage)", effects: ["damage"], damage: "tp" },
  { msg: "Ammunition Bay/Magazine Explosion (+Tp damage)", effects: ["damage"], damage: "tp" },
  { msg: "Fire: Level 3 (+3 damage)", effects: ["damage"], damage: 3 },
  { msg: "Fire: Level 3 (+3 damage)", effects: ["damage"], damage: 3 },
  { msg: "Auxiliary Bridge Hit" },
  { msg: "Auxiliary Bridge Hit" },
  { msg: "Explosive Chain Reaction (+4 damage)", effects: ["damage"], damage: 4 },
  { msg: "Explosive Chain Reaction (+4 damage)", effects: ["damage"], damage: 4 },
  { msg: "All Sensors Out (Offline and no movement until repaired)", effects: ["offline","nomove"], offline: "all", nomove:-1 },
  { msg: "All Sensors Out (Offline and no movement until repaired)", effects: ["offline","nomove"], offline: "all", nomove:-1 },
  { msg: "Shield Power Couplings Down (Sh=0 until repaired)", effects: ["shield"], shield:0 },
  { msg: "Shield Power Couplings Down (Sh=0 until repaired)", effects: ["shield"], shield:0 },
  { msg: "Reactor Containment Failure (Ship explodes)", effects: ["death"] }
];
